SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(HISTORY_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE YEAR(START_DATE) = '2022'
AND MONTH(START_DATE) BETWEEN '8' AND '10'
AND CAR_ID IN (
    SELECT CAR_ID 
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE YEAR(START_DATE) = '2022'
    AND MONTH(START_DATE) BETWEEN '8' AND '10'
    GROUP BY car_id 
    HAVING COUNT(HISTORY_ID)>4) 
GROUP BY CAR_ID, MONTH
HAVING RECORDS>0
ORDER BY MONTH(START_DATE) ASC, CAR_ID DESC;