SELECT (
    CASE
        WHEN (SKILL_CODE & (SELECT sum(CODE) FROM SKILLCODES WHERE CATEGORY LIKE 'Front%')) 
            and SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'PYTHON') THEN 'A'
        WHEN SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME ='C#') THEN 'B'
        WHEN SKILL_CODE & (SELECT sum(CODE) FROM SKILLCODES WHERE CATEGORY LIKE 'Front%') THEN 'C'
    END) as GRADE, ID, EMAIL
FROM DEVELOPERS
GROUP BY GRADE, ID, EMAIL
HAVING GRADE is not null
ORDER BY GRADE, ID;